### ISSUE TITLE
re-harden previous shuttle submissions on every tool change

### ISSUE THREAD

**Issue by proppy** [The-OpenROAD-Project/OpenLane-MPW-CI#16]
It would be neat to run this CI on every changes to the following repo:
- https://github.com/The-OpenROAD-Project/OpenLane/ /cc @donn
- https://github.com/The-OpenROAD-Project/OpenROAD/ /cc @maliberty 
- https://github.com/RTimothyEdwards/magic /cc @RTimothyEdwards
- https://github.com/RTimothyEdwards/open_pdks
- https://github.com/RTimothyEdwards/netgen
- https://github.com/google/skywater-pdk /cc @mithro

is that already the plan?

**Comment by vvbandeira** [comment]
Yes, at least for OpenLane and OpenROAD the goal is to test at least nightly.
For the other repos I am not sure if they will be directly watched, but since they are bundled in OL flow there will be some coverage.
