### ISSUE TITLE
The "designs" directory should have an index file

### ISSUE THREAD

**Issue by mithro** [The-OpenROAD-Project/OpenLane-MPW-CI#32]
The [designs directory](https://github.com/The-OpenROAD-Project/OpenLane-MPW-CI/tree/main/designs) has quite a large number of designs but no information at all about them. It would be good to have a `README.md` file which described some information about each design.

Relevant information would be;
 * Name.
 * Short description.
 * Who made it.
 * Type of design.
 * Where / when it was taped out.
 * Link to the current status on CI.
 * Link to a dashboard which shows the metrics about the design over time.

**Comment by mithro** [comment]
Maybe status / build badges would be good too...

**Comment by vijayank88** [comment]
> The [designs directory](https://github.com/The-OpenROAD-Project/OpenLane-MPW-CI/tree/main/designs) has quite a large number of designs but no information at all about them. It would be good to have a `README.md` file which described some information about each design.
> 
> Relevant information would be;
> 
>     * Name.
> 
>     * Short description.
> 
>     * Who made it.
> 
>     * Type of design.
> 
>     * Where / when it was taped out.
> 
>     * Link to the current status on CI.
> 
>     * Link to a dashboard which shows the metrics about the design over time.

We are maintains a spreadsheet internally, which contain all above details. 

I will make it as markdown format.

**Comment by vijayank88** [comment]
@vvbandeira 
As we are maintaining spreadsheet here: https://docs.google.com/spreadsheets/d/1WEw40LbszfU73tOpUKDtW8G1I-jhOVI5yRYKzGZa8EI/edit#gid=0
Is possible to create a link to such spreadsheet, so whenever we update, its automatically get update here as well?

**Comment by vvbandeira** [comment]
@vijayank88 we could add a URL to the spreadsheet, but I believe that having a README.md index as Tim suggested is a better practice. This way the list is contained in the repo itself.

**Comment by vijayank88** [comment]
@mithro 
Please check this fork https://github.com/vijayank88/OpenLane-MPW-CI/blob/mpw_readme/MPW-2_README.md
Created for MPW-2 shuttle design list and its URL.
Please review and let me know to update or discard any columns from the markdown file.

**Comment by mithro** [comment]
It looks like it is heading in the right direction, but the README should be for the whole directory not a specific MPW? I shouldn't need to understand the efabless MPW runs to understand the contents of this directory.
